---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces/status
  verbs:
  - get
- apiGroups:
  - policy.akuity.io
  resources:
  - namespaceclasses
  - namespaceclassitems
  - namespaceiteminstances
  - namespacestates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.akuity.io
  resources:
  - namespaceclasses/finalizers
  - namespaceclassitems/finalizers
  - namespaceiteminstances/finalizers
  - namespacestates/finalizers
  verbs:
  - update
- apiGroups:
  - policy.akuity.io
  resources:
  - namespaceclasses/status
  - namespaceclassitems/status
  - namespaceiteminstances/status
  - namespacestates/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: '*'
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
